version: "2.1"
services:
  tags_backend:
    build:
      context: https://${GITHUB_ACCESS_TOKEN}:@github.com/sarang-apps/tags-backend.git#develop
    ports:
      - "7000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=tags
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_CONNECTION=postgres
      - EXTERNAL_PORT=7000
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=tags
      - PGHOST=postgres
      - ES_URL=http://elasticsearch:9200/
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - DB_TIMEZONE=+07:00
    links:
      - postgres

  postgres:
    build: ./postgres_docker
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_MULTIPLE_DATABASES=tags,postgres locations,postgres people,postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - PGUSER=postgres
    volumes:
      - dam-db:/var/lib/postgresql/data
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 3s
      timeout: 3s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=baps.apps@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=Bapsdam@123
      - PGADMIN_LISTEN_PORT=80
    depends_on:
      - postgres
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "postgres:pgsql-server"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/"]
      interval: 30s
      timeout: 15s
      retries: 5

volumes:
  dam-db:
  pgadmin-data:

networks: {}
